### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by kamicut** [SocialMediaExchange/muhal#1]
We need to have the site in both English and Arabic. @GrantBaker22 could you provide me with a list of English and Arabic translations of the interface?

**Comment by kamicut** [comment]
@GrantBaker22 I will do my best to come up with words for the interface buttons. I'm thinking that the default interface is arabic, correct?

**Comment by GrantBaker22** [comment]
Yes, default should be Arabic; I will have Abed check it today.

**Comment by kamicut** [comment]
This is being worked on in https://github.com/SocialMediaExchange/muhal/pull/16

**Comment by kamicut** [comment]
Done
