### ISSUE TITLE
Add report page

### ISSUE THREAD

**Issue by kamicut** [SocialMediaExchange/muhal#14]
@GrantBaker22 do we have to add a lot of metadata for this one? It seems like it would be onerous for those reporting a case. What do you think should go here?

**Comment by GrantBaker22** [comment]
Marc could we just add the following fields 

"E-mail" (of the person filing the complaint) 
"Name of the defendant" 
"Platform" 
"Complaint by" 
"Description" 

Then, the information should be forwarded to info@smex.org (maybe info@muhal.org) will try to get this set up today and a message.

**Comment by kamicut** [comment]
Could we do this via google form or mailchimp, or do you want me to collect the form entries and generate the body of an email?

**Comment by kamicut** [comment]
I'm going to mark this as done for now. We can re-open a new ticket for a better implementation
