### ISSUE TITLE
Moving the site to Muhal.org

### ISSUE THREAD

**Issue by GrantBaker22** [SocialMediaExchange/muhal#18]
Marc, 

What do we need to do to make this happen for you?

**Comment by kamicut** [comment]
Do you own the domain @GrantBaker22 ? Our current deployment is on Heroku. If we want to make it stable (so that the server doesn’t sleep), it’ll be $7/month and we can get SSL (https) and custom domains.

**Comment by GrantBaker22** [comment]
We own the domain, www.muhal.org, it is hosted by greenhost.

**Comment by kamicut** [comment]
Done, waiting for DNS
