### ISSUE TITLE
Markup for about page and report a case

### ISSUE THREAD

**Issue by kamicut** [SocialMediaExchange/muhal#9]
What should the about and report page say (in english and arabic) @GrantBaker22 ?

**Comment by GrantBaker22** [comment]
Hi Marc, 

Here is the Google Doc I shared with you: https://docs.google.com/document/d/1vYb6YVo_pbi8b6eV9PXzcd6oa7FJpaAbbxCt1jdf3hM/edit .

**Comment by kamicut** [comment]
Thanks!

**Comment by kamicut** [comment]
I'm going to break this up into 2 issues
